version: "3.7"

services:
  redis:
    image: "redislabs/redistimeseries:1.6.0"
    profiles: ["devel-native", "devel-docker", "prod"]
    restart: unless-stopped
    ports:
      # redis connection
      - "127.0.0.1:6379:6379"

  telestion:
    image: "ghcr.io/fussel178/telestion-project-corfu-sample:##TAG##"
    restart: unless-stopped
    ports:
      # passthroughs TCP EventBus Bridge to allow connections from clients on host
      - "0.0.0.0:9870:9870"
    volumes:
      # pass configuration to container
      - type: bind
        source: "./conf"
        target: "/usr/telestion/telestion-project-corfu-sample/conf"

# rename default docker network
networks:
  default:
    name: telestion-net
